<?xml version="1.0" encoding="utf-8"?><Database Name="Files" Class="DirectumsServiceDataClassesDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JENEKX-PC;Initial Catalog=Files;Persist Security Info=True;User ID=sa" SettingsObjectName="Directums.Service.Properties.Settings" SettingsPropertyName="DirectumsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccessRights" Member="AccessRights">
    <Type Name="AccessRight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdFile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="User_AccessRight" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="File_AccessRight" Member="File" ThisKey="IdFile" OtherKey="Id" Type="File" IsForeignKey="true" />
      <Association Name="Group_AccessRight" Member="Group" ThisKey="IdGroup" OtherKey="Id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Patronymic" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="BornDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IdRootFolder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="User_AccessRight" Member="AccessRights" ThisKey="Id" OtherKey="IdUser" Type="AccessRight" />
      <Association Name="User_File" Member="Files" ThisKey="Id" OtherKey="IdOwner" Type="File" />
      <Association Name="User_HistoryUser" Member="HistoryUsers" ThisKey="Id" OtherKey="IdUser" Type="HistoryUser" />
      <Association Name="User_Message" Member="Messages" ThisKey="Id" OtherKey="IdUserFrom" Type="Message" />
      <Association Name="User_Message1" Member="Messages1" ThisKey="Id" OtherKey="IdUserFor" Type="Message" />
      <Association Name="User_UserGroup" Member="UserGroups" ThisKey="Id" OtherKey="IdUser" Type="UserGroup" />
      <Association Name="Item_User" Member="Item" ThisKey="IdRootFolder" OtherKey="Id" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Extensions" Member="Extensions">
    <Type Name="Extension">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Association Name="Extension_File" Member="Files" ThisKey="Id" OtherKey="IdExtension" Type="File" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdOwner" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="IdExtension" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="File_AccessRight" Member="AccessRights" ThisKey="Id" OtherKey="IdFile" Type="AccessRight" />
      <Association Name="File_FileTag" Member="FileTags" ThisKey="Id" OtherKey="IdFile" Type="FileTag" />
      <Association Name="File_FileVersion" Member="FileVersions" ThisKey="Id" OtherKey="IdFile" Type="FileVersion" />
      <Association Name="File_HistoryFile" Member="HistoryFiles" ThisKey="Id" OtherKey="IdFile" Type="HistoryFile" />
      <Association Name="File_Item" Member="Items" ThisKey="Id" OtherKey="IdFile" Type="Item" />
      <Association Name="Extension_File" Member="Extension" ThisKey="IdExtension" OtherKey="Id" Type="Extension" IsForeignKey="true" />
      <Association Name="User_File" Member="User" ThisKey="IdOwner" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FileTags" Member="FileTags">
    <Type Name="FileTag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdTag" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="File_FileTag" Member="File" ThisKey="IdFile" OtherKey="Id" Type="File" IsForeignKey="true" />
      <Association Name="Tag_FileTag" Member="Tag" ThisKey="IdTag" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FileVersions" Member="FileVersions">
    <Type Name="FileVersion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdFile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Number" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="File_FileVersion" Member="File" ThisKey="IdFile" OtherKey="Id" Type="File" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Groups" Member="Groups">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Group_AccessRight" Member="AccessRights" ThisKey="Id" OtherKey="IdGroup" Type="AccessRight" />
      <Association Name="Group_Message" Member="Messages" ThisKey="Id" OtherKey="IdGroupFor" Type="Message" />
      <Association Name="Group_UserGroup" Member="UserGroups" ThisKey="Id" OtherKey="IdGroup" Type="UserGroup" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryFiles" Member="HistoryFiles">
    <Type Name="HistoryFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IdFile" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Param1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Param2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Param3" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Param4" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="File_HistoryFile" Member="File" ThisKey="IdFile" OtherKey="Id" Type="File" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HistoryUsers" Member="HistoryUsers">
    <Type Name="HistoryUser">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Param1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Param2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Param3" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Column Name="Param4" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
      <Association Name="User_HistoryUser" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IdParent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdFile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Item_User" Member="Users" ThisKey="Id" OtherKey="IdRootFolder" Type="User" />
      <Association Name="Item_Item" Member="Items" ThisKey="Id" OtherKey="IdItem" Type="Item" />
      <Association Name="Item_Item1" Member="Items1" ThisKey="Id" OtherKey="IdParent" Type="Item" />
      <Association Name="File_Item" Member="File" ThisKey="IdFile" OtherKey="Id" Type="File" IsForeignKey="true" />
      <Association Name="Item_Item" Member="Item1" ThisKey="IdItem" OtherKey="Id" Type="Item" IsForeignKey="true" />
      <Association Name="Item_Item1" Member="Item2" ThisKey="IdParent" OtherKey="Id" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdUserFrom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUserFor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdGroupFor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Group_Message" Member="Group" ThisKey="IdGroupFor" OtherKey="Id" Type="Group" IsForeignKey="true" />
      <Association Name="User_Message" Member="User" ThisKey="IdUserFrom" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Message1" Member="User1" ThisKey="IdUserFor" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Options" Member="Options">
    <Type Name="Option">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Association Name="Tag_FileTag" Member="FileTags" ThisKey="Id" OtherKey="IdTag" Type="FileTag" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroups" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdUser" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Group_UserGroup" Member="Group" ThisKey="IdGroup" OtherKey="Id" Type="Group" IsForeignKey="true" />
      <Association Name="User_UserGroup" Member="User" ThisKey="IdUser" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>